### ISSUE TITLE
About Cross-modal Prompt Fusion module

### ISSUE THREAD

**Issue by XiruiTeng** [Kelvin-ywc/LPI#4]
Thank you for your previous answer! However, after reviewing the code, I couldn't find the CPF module, which is used for cross-layer information fusion. Could you let me know which lines in which file contain the implementation of this module? Thanks so much!

**Comment by Kelvin-ywc** [comment]
The Cross-modal Prompt Fusion module is implemented in the BertEncoder class's forward function in the LPI/grounding/maskrcnn_benchmark/modeling/bert/modeling_bert.py file. The code in this section is relatively complex because the GLIP model uses Swin as the visual encoder and BERT as the language encoder. To achieve hierarchical interaction within the encoders, I had to separate and then reassemble Swin and BERT. In the implementation, I disassembled Swin, extracted the required prompts, and passed them to specific layers of BERT.

**Comment by XiruiTeng** [comment]
> The Cross-modal Prompt Fusion module is implemented in the BertEncoder class's forward function in the LPI/grounding/maskrcnn_benchmark/modeling/bert/modeling_bert.py file. The code in this section is relatively complex because the GLIP model uses Swin as the visual encoder and BERT as the language encoder. To achieve hierarchical interaction within the encoders, I had to separate and then reassemble Swin and BERT. In the implementation, I disassembled Swin, extracted the required prompts, and passed them to specific layers of BERT.

Thank you for your reply. I apologize for only reviewing the retrieval code and forgetting to look at the grounding code. Is this module exclusively designed for grounding tasks, or is its implementation for retrieval tasks similar to that for grounding tasks?

**Comment by Kelvin-ywc** [comment]
For the Image-Text Retrieval task, introducing interactions between vision and language would significantly increase the retrieval's time complexity, as each image needs to interact with every text. Therefore, we did not include the cross-modal prompt fusion module in the retrieval task.

In the REC task, since the images and texts are one-to-one corresponding, we incorporated the cross-modal prompt fusion module. Apart from this, there are no differences in the design of the prompts between the two tasks.

**Comment by XiruiTeng** [comment]
> For the Image-Text Retrieval task, introducing interactions between vision and language would significantly increase the retrieval's time complexity, as each image needs to interact with every text. Therefore, we did not include the cross-modal prompt fusion module in the retrieval task.
> 
> In the REC task, since the images and texts are one-to-one corresponding, we incorporated the cross-modal prompt fusion module. Apart from this, there are no differences in the design of the prompts between the two tasks.

Understood. Thank you very much!

**Comment by Kelvin-ywc** [comment]
You're very welcome! If you have any more questions or need further assistance, feel free to ask.
